export const INITIAL_FIELD_STATE = "INITIAL_FIELD_STATE";
export const CORRECT_FIELD_STATE = "CORRECT_FIELD_STATE";
export const WRONG_FIELD_STATE = "WRONG_FIELD_STATE";
export const OVER_FIELD_STATE = "OVER_FIELD_STATE";
